services:
  api:
    container_name: conduit-api
    build: .
    restart: always
    env_file: .env
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - octane-net

networks:
  octane-net:
    external: true