name: Deploy Conduit Core

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    uses: shubh305/octanebrew-platform/.github/workflows/ssh-deploy.yml@main
    with:
      working-directory: "~/conduit-core" 
      compose-file: "docker-compose.yml"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
